### PR TITLE
Fix jest error by mocking profanity_filter in chat_markup.test.tsx.

### PR DESCRIPTION
**Pull request by benjaminpjones**
Fixes shippable error

## Proposed Changes

  - mock profanity_filter in chat_markup.test.tsx

### CODE REVIEW

**Comment by GreenAsJade** [comment]
@benjaminpjones Delighted to have this fix available.

Out of curiosity, why is it to be applied to my fork, and not the main devel?

**Comment by benjaminpjones** [comment]
Sure!

>Out of curiosity, why is it to be applied to my fork, and not the main devel?

I thought this would save you the trouble of waiting for a merge and pulling in (shippable isn't broken on the main branch).

Happy to push to `devel` if preferable!

**Comment by GreenAsJade** [comment]
This is the mystery for me - why is shippable only broken on my fork?

**Comment by benjaminpjones** [comment]
So it's not your fault, it's the fact that I haven't fully mocked out modules in the tests (will do now that I know there's a problem, just didn't have much experience with Jest before writing them!)

What happened is `chat_markup` has a dependency on `data`. Your PR updated `data` to depend on `io`.  Jest seems to disagree with outside libs, which caused shippable to break.

**Comment by benjaminpjones** [comment]
Here's the full dependency chain:

```
chat_markup.test.tsx
-> chat_markup.tsx
-> profanity_filter.ts
-> preferences.ts
-> data.ts
(ADDED IN THIS BRANCH)
-> remote_storage.ts
-> sockets.ts
-> io()
```

**Comment by GreenAsJade** [comment]
Thanks for the explanation!

**Pull request merged**
